# Permalinks
permalink:           /:title
# Setup
title:               com.surizz.blog
tagline:             'dev_history_repository_'
description:         '개발의 흔적들<br>2020 ~ NHN'
url:                 http://Surizz.github.io
baseurl:             ''
plugins:
  - jekyll-paginate
paginate:            5

# About/contact
author:
  name:              Surizz
  url:               https://Surizz.github.io
  email:             yhspace33@gmail.com

# Custom vars
version:             1.0.0